### PR TITLE
[WIP] Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by raphaellueckl**

### CODE REVIEW

**Comment by jackblackCH** [comment]
Missing empty end of line

**Comment by jackblackCH** [comment]
We should work with consistent node versions in all local, dev, prod etc. environments. AFAIK AXA has to use node 8 for some reasons? @LucaMele

**Comment by LucaMele** [comment]
@jackblackCH AXA has ONLY Node 6 and 8.8.1 on their Cloud Open Shift Platforms and Jenkins... but i think on azure we are free.. maybe @raphaellueckl check with Shelko if we are free to choose the Node Version we want

**Comment by raphaellueckl** [comment]
old

**Pull request closed without merging**
