### PR TITLE
added lifecycle test

### PR DESCRIPTION
**Pull request by AndyOGo**
Experiment for #335 

Not meant to be merged.
 
 # How Has This Been Tested?
 
In chrome's console:

```js
var test = document.getElementById('axa-test');
// this triggers attributeChangeCallback only if foo is defined in observeAttributes
test.setAttribute('foo', 'bar');
// property changes do not trigger attributeChangeCallback, even if foo is defined in observeAttributes
test.foo = 'baz';
// not a single lifecycle event triggers, DOM gets corrupted
test.innerText = 'foo bar';
// not a single lifecycle event triggers, DOM gets corrupted
test.innerHTML = '<span>foo bar</span>';
// not a single lifecycle event triggers, DOM gets corrupted
test.appendChild(document.createElement('div'))
```

### CODE REVIEW

**Comment by LucaMele** [comment]
why is jenkins failing?

**Comment by AndyOGo** [comment]
I don't know, may I have lint issue... will check

**Comment by AndyOGo** [comment]
@LucaMele 
Monkey Patching works quite well, the only issue I see is that the whole DOM subtree is rebuild every time, which could lead to performance implications. So far I have monkey patch `innerText`, `innerHTML` and `appendChild`, we may need more... or `textContent` for cross browser compatibility.

**Comment by AndyOGo** [comment]
@LucaMele 
I just added an interval to rerender every second automatically for testing purpose.
At the moment it will rerender whether something has changed or not.

**Comment by AndyOGo** [comment]
@LucaMele 
Since this re-renders the whole DOM subtree we will face the following issues:

- References to DOM nodes inside the subtree get out-of-sync
- Performance

**Comment by AndyOGo** [comment]
Since we just have merge real incremental rendering this can be closed :)

**Pull request closed without merging**
