### PR TITLE
2441: update package.json version of released components

### LINKED ISSUE #2441: Update package.json version of released components
After the last pattern library release, the version are not updated in the package.json files of the updated components. 

Ex: Footer: Release Version 6.2.0, Version declaired in package.json 6.1.0

### PR DESCRIPTION
**Pull request by thomas-krueger-axa**
Fixes #2441 

# Merge Checklist:
- [ ] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch-webhub-cloud/pattern-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [ ] Tests are sufficient.
- [ ] Documentation is up to date.
- [ ] Changelog is up to date.
- [ ] Typescript typings for properties are up to date.
- [ ] Designers approved changes or no approval needed.
- [ ] Dependencies to other components still work.

### CODE REVIEW

**Review by marcwelz — APPROVED** [review]

**Review by marcwelz — CHANGES_REQUESTED** [review]
Did you update every component? For example the axa-table version has not been updated

As far I am concerned every component needs an update.

**Comment by thomas-krueger-axa** [comment]
> Did you update every component? For example the axa-table version has not been updated
> 
> As far I am concerned every component needs an update.

Lerna is asking for all the components, so i updated all of them.

**Comment by marcwelz** [comment]
> Lerna is asking for all the components, so i updated all of them.

What do you mean exactly? You didnt update the table component for example. The newest package version is 5.1.1

**Review by marcwelz — DISMISSED** [review]
Lerna doesnt seem to need to update this components, probably because there are no dependencies.

LGTM

**Review by stefan-17367837 — APPROVED** [review]

**Pull request merged**
