### PR TITLE
Feature/update icon images

### LINKED ISSUE #1731: Update icons (and images) from Figma and add all materials icons
At PR https://github.com/axa-ch/patterns-library/pull/1729 the icons (referenced by icon component) are updated from Figma. But they have internal bit more "margins". So they look a little bit smaller than the others.

TODO:
- Update all the icons from Figma. And update images as well makes sense.
- Message @sabine-schneider1990 if finished (#1915)

### PR DESCRIPTION
**Pull request by 01231**
Fixes #1731

TODO: Use `currentColor` in all 294 Files

# Done is when (DoD):
- [ ] Modifications within components are reflected by tests.
- [ ] A self-review of the code has been performed.
- [ ] The modified component properties have been added to the typescript typings.
- [ ] Potential design changes have been reviewed by a designer.
- [ ] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [ ] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [ ] The modifications are shortly added to CHANGELOG.md with the issue number.
- [ ] The modifications still work in IE.
- [ ] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

### CODE REVIEW

**Review by 01231 — COMMENTED** [review]
looks great except cars.svg.js

**Review by danyball — COMMENTED** [review]
Wow 581 files changed. Just had a short overview :) Maybe the emtpy spaces at the svg filenames could be a problem? `24 x 7.svg`

**Comment by 01231** [comment]
LGTM

**Review by raphaellueckl — APPROVED** [review]
nice

**Pull request merged**
