### PR TITLE
try to fix menu behaivour

### PR DESCRIPTION
**Pull request by LucaMele**

### CODE REVIEW

**Comment by LucaMele** [comment]
@AndyOGo please check & test. I will redeploy dev asap this is merged. I dont like that the axa header behaves slightly different then this and will try to find out why.

**Comment by LucaMele** [comment]
fixes #314

**Comment by AndyOGo** [comment]
The fundamental difference of axa.ch is that if a menu-item is clicked a whole pageload is triggered. So it doesn't matter if the sub-navigation is closed or not by JS.

But in case of an SPA and client side routing, it matters.

**Comment by LucaMele** [comment]
yes true. Im referring that the same menu settings with classes behavies diffrent on axa.ch and here (so both not in SPA modus)

**Comment by LucaMele** [comment]
if we check the dev menu, its differently broken

**Comment by LucaMele** [comment]
im not speaking about submenu, im speking about top level menu. i understand that if u have anchor tags it does not do a page reload (which is this bug fix here)

**Comment by AndyOGo** [comment]
@LucaMele 
But we have hash changes, which we don't have at axa.ch

**Comment by LucaMele** [comment]
ok im not eplining myself. Haschanges comes from sub menu. The top menu is the issue. Here in the p-lib the top menu is fine and works. Same top menu in axa.ch triggers a page reload as soon as u press it. Not the submenu. the top menu. This hasnt to do anything with this fix. The stroke js prevent default it and thats why i did work so far on axa.ch. But in the patterns library that prevent default was not needed. This is inconrgouency thats scares me.

**Comment by AndyOGo** [comment]
stroke-not-moving

**Comment by LucaMele** [comment]
shit ok will fix it. Is the return

**Comment by AndyOGo** [comment]
Alright.
The top navigation should only prevent the default action if it has a sub navigation.

Let's go back to the basics, how is navigation's design originally intended.

- Sub Navigation entries are shown on `click` - in fact clicking the same item again closes it. So it's intended to be a toggle.
- A stroke is displayed if:
   - The current menu item is active or one of it's children is active
   - An optional sub-navigation is actiaved

**Regarding Stroke's Animations**

The interactive part consists of three different animations - one for `entering` an interactive state, one for `moving` between items and one for `leaving` the interactive state

has an active item | enter | move | leave
---|---|---|---
Nope | Animate the `height` from `0` to `4px` | Animate the `left` to the next items position | Animate the `height` from `4px` to `0`
Yes | Hide the stroke at the active element | nothing | Show the stroke at the active element 

**How do events related to those interactive states**

- first `click` -> `enter`
   - another item `click` -> `move`
   - second `click` on same item -> `leave`
   - clicking `outside` of the navigation -> `leave`
   - hitting `ESC` key -> `leave`

To make it even more complex the transition between those states is also handled by `transitionend` events. And the correct Stroke's position in case of `resize`, `orientation` events is also handled properly.

**Comment by LucaMele** [comment]
fixes: #320, #316, #314

**Pull request merged**
