### PR TITLE
axa-datepicker: enforce consistent date format on blur

### LINKED ISSUE #2068: axa-datepicker inputfield value should always have 2-digit day and month parts
Ken Brossi reported a designers' consensus on standardizing the visible day and month parts of a axa-datepicker inputfield value towards 2 digits:  21.2.2020 => 21.**0**2.2020, 9.10.1963 => **0**9.10.1963, etc.

Users may continue to enter valid numerical dates without a leading zero for months January-September or the first 9 days of a month, but the visible date in the input field will be rewritten to conform to 2-digit days and months on blur.

### LINKED ISSUE #2084: Playwright testing is not as robust as it should be
In running Playwright as part of `npm run test` I found some issues:

- my feeble laptop could get close to the configured per-test timeout (15s): this should be increased
- due to transient dev-webserver caching issue I had a broken JSON config preventing said webserver from starting up, but all error reporting was suppressed: do not suppress valuable error info
- there was no config to start a playwright-controlled browser in *headful* mode: this should be made possible

Fix these issues.

### PR DESCRIPTION
**Pull request by markus-walther**
Fixes #2068.
Fixes #2084.

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [x] Modifications still work in IE.
- [x] Documentation is up to date.
- [x] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [x] Designers approved changes or no approval needed.
- [x] Dependencies to other components still work.

### CODE REVIEW

**Review by danyball — CHANGES_REQUESTED** [review]
1) If you choose the date over the dropdown the date is not formatted:

image

2) i just set headless to false and run test-ui script. He opens two chrome windows and then build the storybook app. And the build was very slow. After it finished building i got this error:

``` FAIL   browser: chromium  src/components/10-atoms/button/pw.ui.test.js (32.386s)
  ● should render button

    thrown: "Exceeded timeout of 30000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

```
-> why he opens up the Testcafe tests BEFORE storybook has builded successful?

3) the code changes are good. no comments here.

**Comment by markus-walther** [comment]
Good catch regarding the date choice via calendar clicking - fixed.

**Review by danyball — CHANGES_REQUESTED** [review]
Now the tests are failing on azure. Will re-test if the feature branch deployed your changes.

Another question: Why did you make the 2-digit-format optionally? Is there a case to need the "old" format style?

**Comment by markus-walther** [comment]
> Another question: Why did you make the 2-digit-format optionally? Is there a case to need the "old" format style?

The usual backwards compatibility reason... people have used it with the old behaviour, and for controlled mode any kind of custom formatting can of course be implemented, so my modification must not interfere.

**Comment by markus-walther** [comment]
On `should render button

    thrown: "Exceeded timeout of 30000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

-> why he opens up the Testcafe tests BEFORE storybook has builded successful?`

I had this once, too. IMHO this is playwright/Jest being occasionally flakey...

**Review by danyball — APPROVED** [review]
a last question via slack....

**Pull request merged**
