### PR TITLE
feature/1944_brand-elements-margin

### LINKED ISSUE #1944: Add Margin to brand element pages
I think it would make sense to adapt the margin of our new welcome page (+the other pages) to the brand element pages.

**Welcome Page**
Screenshot 2020-09-01 at 09 18 13

**Brand Element Pages**
Screenshot 2020-09-01 at 09 20 31

### PR DESCRIPTION
**Pull request by raphael-suter**
Fixes #1944 

# Merge Checklist:
- [x] Code selfreview has been performed ([Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)).
- [x] Tests are sufficient.
- [x] Modifications still work in IE.
- [x] Documentation is up to date.
- [x] Changelog is up to date.
- [x] Typescript typings for properties are up to date.
- [x] Designers approved changes or no approval needed.

### CODE REVIEW

**Review by danyball — CHANGES_REQUESTED** [review]
Please adapt the fonts and fontsizes as well. The icon page looks a bit lonely with this huge margins and the small text.

**Review by 01231 — CHANGES_REQUESTED** [review]
Font looks broken
Screenshot 2020-09-28 at 16 12 56

**Comment by danyball** [comment]
> Font looks broken
> Screenshot 2020-09-28 at 16 12 56

That is not a new bug. But a quixfix is to use the axa-text component for those texts. Maybe raphi can implement that on that pr?!

**Comment by 01231** [comment]
> > Font looks broken
> > Screenshot 2020-09-28 at 16 12 56
> 
> That is not a new bug. But a quixfix is to use the axa-text component for those texts. Maybe raphi can implement that on that pr?!

This is what is looks on prod
Screenshot 2020-09-28 at 16 25 06

**Review by 01231 — APPROVED** [review]
LGTM

**Review by danyball — APPROVED** [review]

**Pull request merged**
