### PR TITLE
Add changelog to storybook readme panel

### LINKED ISSUE #1562: Can not open changelog
After clicking on the link in the Storybook readme to open the changelog, the following messages appear on the window:

### patterns.axa.ch
image

### PR DESCRIPTION
**Pull request by danyball**
This is a suggestion to solve the issue. If ok -> replace all components.

Fixes #1562

# Done is when (DoD):
- [ ] I have added UI/Unit tests for my changes
- [ ] I added modified component properties to the typescript typings
- [ ] Design has been reviewed with (here name of reviewer)
- [ ] My changes are accordingly to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)
- [ ] Old tests and eslint rule are not broken
- [ ] My changes are well documented in the README and showcased in the stories 
- [ ] Tested with IE

# Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas (focus on **WHY**)
- [ ] I have made/updated the ChangeLog Section in the README

### CODE REVIEW

**Review by 01231 — COMMENTED** [review]
It works great, but wasn't the problem that people will never scroll down in the readme to read the migration notes? How about an extra tab (like knobs)?

**Review by LucaMele — APPROVED** [review]
LGTM. But needs to be done for all components right?

**Comment by danyball** [comment]
> It works great, but wasn't the problem that people will never scroll down in the readme to read the migration notes? How about an extra tab (like knobs)?

Yes, i hoped to implement it that way. But only storybook plugins can create tabs. We could write such a plugin but that can be expensive?!

What about putting Changelog at the top for a first try?

**Comment by danyball** [comment]
> LGTM. But needs to be done for all components right?

Jep. That will be a new issue if this one is ok.

**Comment by danyball** [comment]
- evtl über anchor
- sb plugin: addonAPI.register (addons.js)

**Review by 01231 — APPROVED** [review]

**Comment by danyball** [comment]
Notice for me: changelog-title-string is not present if newest changelog versions

**Pull request closed without merging**
