### PR TITLE
Bugfix/duplicate stylesheets

### LINKED ISSUE #1727: Multiple instances of a components cause multiple CSS appends to document head
IS: Multiple component make multiple entries in the head
SHOULD: for one component always and only one css should be rendererd in the `head` tag. Issue relys in NO Shadow. example: https://www.acc.axa.ch/de/rechner/rechtsschutzversicherung.html#/start

INFO: This has nothing to do with the possibility of having multiple versions of the component. 1 HTML = 1 JS = 1 CSS. This must be there as is a constraint of custom element itself.  Once we have done a multiversion stratgey, we will most likly end up in having CE Names like this: `axa-button-1-1-1`. Here again rule apply: 1 HTML = 1 JS = 1 CSS. Therefore the fix in no-shadow dom is also in the best intrest of Versioning and multi tenant.

### PR DESCRIPTION
**Pull request by markus-walther**
Fixes #1727.

**Replaces stale PR https://github.com/axa-ch/patterns-library/pull/1736**

# Done is when (DoD):
- [x] Modifications within components are reflected by tests.
- [x] A self-review of the code has been performed.
- [x] The modified component properties have been added to the typescript typings.
- [x] Potential design changes have been reviewed by a designer.
- [x] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [x] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [x] The modifications are shortly added to CHANGELOG.md with the issue number.
- [x] The modifications still work in IE.
- [x] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

Steps left for thorough review, _reduced_ requirements compared to now-stale PR:

- [x] Is there a .css file in the export?
- [x]  review sass-loader code for side effects other than head insertion
- [x] sample testing of 6 most used components: React, lib export
- [x] sample testing of 6 most used components:  native, dist export

Informal proof that the fix is correct: https://gist.github.com/markus-walther/c50ec05d645eaa4e6c7b71ced20c56cf

### CODE REVIEW

**Review by danyball — DISMISSED** [review]
LGTM. Tested on SB@chrome and IE. And on pure html project. Should we test the checklist of the other PR?

**Comment by markus-walther** [comment]
> LGTM. Tested on SB@chrome and IE. And on pure html project. Should we test the checklist of the other PR?

We should at least selectively test the checklist of the other PR. That burden is on me.

**Comment by markus-walther** [comment]
Rollup-plugin-sass is here: https://github.com/differui/rollup-plugin-sass/blob/master/src/index.js.

It does the &lt;head&gt; insertion if `index: true`.

Code inspection does not show adverse side effects when `index: false`.

**Comment by markus-walther** [comment]
https://github.com/axa-ch/pod-aem-patterns-library lists the following components:

    "@axa-ch/button": "5.0.4",
    "@axa-ch/button-link": "2.1.10",
    "@axa-ch/checkbox": "4.0.3",
    "@axa-ch/commercial-hero-banner": "1.1.13",
    "@axa-ch/container": "1.0.17",
    "@axa-ch/cookie-disclaimer": "1.0.4",
    "@axa-ch/datepicker": "7.0.7",
    "@axa-ch/dropdown": "7.0.2",
    "@axa-ch/fieldset": "1.2.4",
    "@axa-ch/footer": "3.0.8",
    "@axa-ch/footer-small": "3.0.6",
    "@axa-ch/input-text": "3.0.5",
    "@axa-ch/link": "4.0.4",
    "@axa-ch/materials": "2.0.1",
    "@axa-ch/patterns-library-polyfill": "1.5.1",
    "@axa-ch/policy-features": "1.0.9",
    "@axa-ch/radio": "1.1.9",
    "@axa-ch/testimonials": "1.0.3",
    "@axa-ch/textarea": "1.5.5"

**Comment by markus-walther** [comment]
The 'sample testing under different scenarios' checklist item requires https://github.com/axa-ch/patterns-library/issues/1890 to be solved.

I.e., we need something like a kitchen-sink page generator where each component is represented in a sensible default configuration.

**Comment by danyball** [comment]
> The 'sample testing under different scenarios' checklist item requires #1890 to be solved.
> 
> I.e., we need something like a kitchen-sink page generator where each component is represented in a sensible default configuration.

What about a html parser that loads our SB and get all the components html (which has the knobs defaults) and puts the snippets on one big html page?!

**Comment by markus-walther** [comment]
Here is a screenshot of the DOM tree of an React Test Pod with 2x the six most-used components:
React Test Pod with 2x six most-used components

Nicely shows how document-head component styles are attached only once after the fix, despite n=2 instances per component. 

Notable complication is versioning: unversioned datepicker contains internally-versioned dropdown, leading to a versioned dropdown styling in addition to the  unversioned styling caused by the 2 standalone dropdown instances on the same page.
This is correct and expected under component versioning; duplication could be avoided by using numerically-versioned standalone dropdown instances instead.

Here is the patch file showing the src/ folder of a create-pod-app-manufactured local pod used for this test:

[create-pod-app-tmp-src-patch.txt](https://github.com/axa-ch/patterns-library/files/4996300/create-pod-app-tmp-src-patch.txt)

The test was performed by copying /lib/index.* of relevant components from the bug-fixed branch over to node_modules of the local pod.

**Comment by danyball** [comment]
>  manual major-alpha test release

These changes do not have any breaking changes. Please publish components with a bugfix-release.

**Comment by danyball** [comment]
What about to create a static html page with these 6 most-recently used components (dist folder) and adding it to PL/SB-Build and UI Test it?

**Review by danyball — DISMISSED** [review]
Pls check my comments

**Comment by markus-walther** [comment]
> What about to create a static html page with these 6 most-recently used components (dist folder) and adding it to PL/SB-Build and UI Test it?

Will do, good suggestion!

**Comment by markus-walther** [comment]
> > What about to create a static html page with these 6 most-recently used components (dist folder) and adding it to PL/SB-Build and UI Test it?
> 
> Will do, good suggestion!


[six-components-dist-patch.txt](https://github.com/axa-ch/patterns-library/files/5014888/six-components-dist-patch.txt)

**Comment by markus-walther** [comment]
The observed head insertion of axa-container styling in an earlier stage of the dist/lib experiments featuring the six most popular components was due to a reference to a node_modules version of axa-container that still contained the unwanted ___$insertStyle. Manually overwriting it with artifacts from a fresh build resulted in the absence of unexplained head insertion of styles.

Therefore we can safely conclude that this problem will be solved once all components have been re-released to npm following the merge of this PR.

**Review by LucaMele — DISMISSED** [review]
LGTM

**Pull request closed without merging**
