### PR TITLE
start trying enabling windooof

### PR DESCRIPTION
**Pull request by AndyOGo**
improves #503 

Changes proposed in this pull request:

 - try to make windows work

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AndyOGo** [comment]
@LucaMele 
@mjenny 
So we get logging output now and the created child-process seem to exit.
But **Windows** shows many more open processes for `npm`/`node` scripts. And this happens also for `npm install` 🤔

**Comment by AndyOGo** [comment]
Windows is super slow...
https://github.com/sindresorhus/execa/issues/142

**Comment by AndyOGo** [comment]
@LucaMele 
Turns out that the release script would actually work, but is super slow on windows (`npm` command take more than **3 minutes** to complete)

https://github.com/nodejs/node/issues/3145

**Comment by AndyOGo** [comment]
@LucaMele 
Indeed, I agree Windows is silly madness 🤕 
But check this PR #553 
I finally found the culprit being `npm`'s usage of `update-notifier`, which lacks support of proxies...

**Comment by AndyOGo** [comment]
Therefore this PR can be closed, if haven't any work we want to keep

**Comment by AndyOGo** [comment]
@mele, I would rather delete this PR, cause I created a new one, with a working workaround, what do you think?

**Comment by LucaMele** [comment]
@AndyOGo , your PR, your desicion :)

**Comment by AndyOGo** [comment]
@LucaMele 
Alright. So we face primarily two issues on Windows:

1. Slow scripted `npm` command caused by `update-notifier` not supporting proxies and thus awaiting a timeout of 3 minutes
2. Several node processes start but don't exit at windows - again `update-notifier` spawns new child process to make their stuff

All of this should be fixed by disabling `update-notifier` in #553 

If all is working as expected now, forcefully killing process should not be needed anymore... so I would just close this PR

**Pull request closed without merging**
