### PR TITLE
Refactor icon search and display only material icon names

### LINKED ISSUE #1640: Remove path characters from materials overview
Screenshot 2020-01-28 at 12 53 14

### PR DESCRIPTION
**Pull request by raphaellueckl**
Fixes #1640 

# Done is when (DoD):
- [x] Modifications within components are reflected by tests.
- [x] A self-review of the code has been performed.
- [x] The modified component properties have been added to the typescript typings.
- [x] Potential design changes have been reviewed by a designer.
- [x] The modifications are well documented (README.md, etc.) and showcased in the stories.
- [x] The modifications are documented in the code, particularly in hard-to-understand areas (focus on **WHY**).
- [x] The modifications are shortly added to CHANGELOG.md with the issue number.
- [x] The modifications still work in IE.
- [x] The modifications are according to our [Best Practices](https://github.com/axa-ch/patterns-library/blob/develop/CONTRIBUTION.md#best-practices)

### CODE REVIEW

**Review by danyball — COMMENTED** [review]
Isn't it useful to know that the files have the ending ".svg.js" ? If you want to import a icon you have to know that the filename is "xyz.svg.js"

**Comment by raphaellueckl** [comment]
@danyball If you use the axa-icon component, this details does not matter. It will not work when you also provide the ending. Other than that, I would say, everyone uses autocompletion. and we would otherwise think about providing the whole path. That might be a useful addition. Instead of 2 columns, having 3 and one containing the path from `@axa-ch/materials/` on.

What I would recommend over what you say is, that we adapt the filename itself. Because `.svg.js` is kind of a weird file endling and we have eslint rules that say we should not import the whole file including extension. So currently, when you import and SVG from a js file, the import looks like this: `import checkmark from '@axa-ch/materials/icons/checkmark.svg'`. It looks like an SVG is being imported, while javascript just adds a `.js` at the end automatically. What you actually import with this expression, is a javascript file.

What do you think?

**Comment by danyball** [comment]
@raphaellueckl first paragraph: jep. Providing the whole path to copy&paste would be great. like `@axa-ch/materials/icons/checkmark.svg`

second: Oh yes good idea. While creating the js file out of the svg, we should rename that file. Something like "xasdf-svg.js"

**Review by 01231 — APPROVED** [review]
Nice

**Review by danyball — APPROVED** [review]

**Pull request merged**
