### PR TITLE
breakes built-in ie but fixes with-react

### PR DESCRIPTION
**Pull request by LucaMele**
Fixes https://github.com/axa-ch/patterns-library-examples/issues/12.

Changes proposed in this pull request:
@AndyOGo this PR fixes `with-react` in IE for AEM, Patterns-Library and Patterns-Library-Examples.
@AndyOGo it brakes built-in ONLY on IE (Safari, EDGE, FF and Chrome worked with built-ins).

### CODE REVIEW

**Comment by LucaMele** [comment]
@AndyOGo , we need this so that we can release AEM and the form refactored so i guess not working built in in IE is the minor issue and we have more time to find out why

**Comment by AndyOGo** [comment]
@LucaMele 
Well that's so unfortunate, WebReflection's polyfill is the only battle tested and feature complete polyfill.
And it is really weird that our preview works across browsers, but the consumed patterns-library doesn't 😕 

Reverting `built-in` support is a regression honestly.
And I think that something is going mad during build or transpilation time.

Please do what you prefer.
I can totally see, that this should be released at AEM right now.

**Comment by LucaMele** [comment]
@AndyOGo is weird combo between with-react and the "battle" proofed polyfill. And actually our preview does not work either: https://axa-ch.github.io/patterns-library/react.html

**Comment by AndyOGo** [comment]
Jep but that is since the build broke...

**Comment by LucaMele** [comment]
I will sleep it over, but in worst case i have to merge. But u can test, built in works everywhere apart of IE so is fine

**Comment by LucaMele** [comment]
@AndyOGo i think it has other issues as well. I will close it and try again tomorrow

**Comment by AndyOGo** [comment]
@LucaMele 
Do tested `built-in` in safari? and it worked?
I think they should be broken in all non-custom-element browsers and Safari

**Comment by LucaMele** [comment]
@AndyOGo yes they did with webcomponents and built in polyfill but in ie some console error came so i gave up

**Pull request closed without merging**
