### PR TITLE
Add AXA Design System guidelines with Gatsby

### PR DESCRIPTION
**Pull request by flexbox**
Hey
I already spoke with @LucaMele about this

Here in 🇫🇷 I need to ship kind of "Marketing pages" for developer and designer.
Storybook is a great tool but it only ticks with front-end developers.
As a solution here is a Gatsby website who consume the axa-ch web components

The preview is available on netlify
https://axa-design-system.netlify.app/

The documentation is on [/docs/readme.md](https://github.com/team-haigo/patterns-library/tree/develop/docs)

There is also some issues on 
https://github.com/team-haigo/patterns-library/issues
to align the branding guidelines with yours.

As a next step let me know if you want to merge it to have a single source of truth for all the branding ressources.

### CODE REVIEW

**Comment by danyball** [comment]
The App looks quite nice. Much more modern than our technical storybook. We have to discuss internally if we want to provide 2 Showcases or just one for devs and business.

**Comment by flexbox** [comment]
Hello @danyball 

I had an introduction talk (to understand how it works) with @raphaellueckl about it.

If something isn't clear feel free to comment and I will update the setup on the README 😉

**Comment by 01231** [comment]
Hey @flexbox, I cherry picked a lot from your preview. Thanks a lot. It was a great inspiration.
Closing this one, because we have our own PR.

**Comment by flexbox** [comment]
No worries!

Glad it helped!

**Pull request closed without merging**
