### PR TITLE
Bridge children of custom elements and remove dom ready

### LINKED ISSUE #515: Using it in axa.ch and without waiting ondomready crahes the flattened DOM
this: 

```html
<axa-cookie-disclaimer fixed button-name="Akzeptieren" title="Datenschutzbestimmungen" classes="o-cookie-disclaimer">
  <p>
    Wir verwenden Cookies und Analyse Tools, um die Nutzerfreundlichkeit der Internet-Seite zu verbessern und die Werbung von AXA und Werbepartnern zu personalisieren. Weitere Infos:
    <axa-link color="white" icons-path-prefix="/etc/clientlibs/axa/frontend-lib/images/icons-v2.svg#" href="/content/axa/de/informationen/datenschutz.html" arrow>
      Datenschutz
    </axa-link>
  </p>
</axa-cookie-disclaimer>
```

### PR DESCRIPTION
**Pull request by AndyOGo**
Fixes #515 

Changes proposed in this pull request:

 -
 -
 -

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
 
 # How Has This Been Tested?
 
 
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AndyOGo** [comment]
Unfortunately after removing `DOMContentLoaded` event from `defineOnce` it still works.
@LucaMele How can I reproduce the problem?

children-local-dom-move

**Comment by AndyOGo** [comment]
@LucaMele 
Is it possible that the order of loading components is significant 🤔

**Comment by LucaMele** [comment]
Patterns lib did always work. Issue is when using it on AXA ch

**Comment by AndyOGo** [comment]
https://unpkg.com/@axa-ch/patterns-library@2.0.1-beta.165/lib/components/o-cookie-disclaimer/index.js

**Comment by AndyOGo** [comment]
@LucaMele 
No worries, I removed it because I wanted to see the bug and investigate on the bug.
But unfortunately I don't have this bug locally 😞 

So first we need to find a reliable reproduction of the issue...

**Comment by AndyOGo** [comment]
I started to get a reproduction, but still not succesfull...

https://stackblitz.com/edit/js-iut3ou

**Comment by AndyOGo** [comment]
Turned out, order is important.

If someone uses custom elements after their registration (as it's done for `<axa-cookie-disclaimer>`) then they can get messed up.
As soon as i revert the order, they work 🎉 
Though that of course should not make any difference 🤔 

screen shot 2018-07-09 at 18 20 21

**Comment by LucaMele** [comment]
Please fix travis

**Pull request merged**
