### PR TITLE
add define element decorator

### PR DESCRIPTION
**Pull request by TheDadi**
WIP Fixes # 391

Changes proposed in this pull request:

 -
 -
 -

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
 
 # How Has This Been Tested?
 
 Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
 
 # Checklist:
 
 - [ ] My code follows the style guidelines of this project
 - [ ] I have performed a self-review of my own code
 - [ ] I have commented my code, particularly in hard-to-understand areas
 - [ ] I have made corresponding changes to the documentation
 - [ ] My changes generate no new warnings
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by LucaMele** [comment]
Thanks @TheDadi . Please other opinions on this. We have to choose between easier development or easier integration in other repos.

**Comment by AndyOGo** [comment]
I think this is good.
And we need proper builds - **MJS** and some old **UMD**.
That will solve consumers needing our babel plugins

**Comment by LucaMele** [comment]
Ok then we can merge and should focus to do this different module loaders asap

**Comment by AndyOGo** [comment]
**Breaking Changes:** Please migrate before merging
https://github.com/axa-ch/patterns-library/releases/tag/v2.0.1-beta.217

**Pull request closed without merging**
