### PR TITLE
Add @storybook/addon-a11y

### LINKED ISSUE #1791: Use a11y storybook plugin
Heres the PR: https://github.com/axa-ch/patterns-library/pull/1787

- [ ] check if there are no performance issues (build time and on runtime)

- [ ] check that plugin - is it maintained usw...

- [ ] add that plugin to all the stories that are relevant to that (f.a. is `colors` page that is mentioned in PR not relevant)

### PR DESCRIPTION
**Pull request by flexbox**
Fixes #1791 

In our efforts to help more customers we need better accessibility in our components.
This is hard when you don't have direct feedback.

Solved with `addDecorator(withA11y);` on stories config

image

Fixes #(issue)

# Done is when (DoD):
- [x] A self-review of the code has been performed.
- [x] The modifications are well documented (README.md, etc.) and showcased in the stories.

### CODE REVIEW

**Comment by danyball** [comment]
Thanks for your PR. Good idea, but we dont want to show everyone our accessible mistakes :) So, a storybook plugin is not our way to go. But something like a a11y test while building/testing would be helpful.

**Review by LucaMele — COMMENTED** [review]
LGTM. I wait for one more review in order to approve

**Comment by LucaMele** [comment]
@danyball i would merge and do your suggestion as well. We have nothing to hide :)

**Comment by flexbox** [comment]
@danyball You made a good point, but the purpose of this plug-in is fixing issues while you are coding.
Like ESLint / Prettier, straight in your editor.
If you check during the build step it's too far from the "coding momentum" and frustrating experience for the dev because some #a11y can't be easily fixed.
The same occurs with performance, fixing an issue introduce a bug and fix this bug introduce an issue 😂 

@LucaMele I think you can check for silents check / warning messages and not a 0 or 1 situation. Blocking the build for #a11y could slow down the velocity of shipping features.

**Comment by LucaMele** [comment]
@flexbox, good points, thank you. We will discuss it on Monday when the whole team is here. Thank you

**Comment by danyball** [comment]
We decided to use that storybook plugin. We will have a closer look at that plugin and than merge that.

**Review by LucaMele — APPROVED** [review]

**Review by raphaellueckl — APPROVED** [review]

**Pull request merged**
